# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0004_auto_20171115_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='form_message',
        ),
    ]
