# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:28
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0006_auto_20171128_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[400, 400], upload_to='assets/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.PriceField(currency='USD', decimal_places=2, max_digits=12, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[100, 100], upload_to='assets/images'),
        ),
    ]
